// Generates examples/dry-run-report.{md,json} from the synthetic test company
// (invented names, ".example" domain). No network access.
import { writeFileSync } from "node:fs";
import { runLookup } from "../opencomputer/agents/funding/lib/lookup";
import { compactReport, renderReport } from "../opencomputer/agents/funding/lib/report";
import { UnavailableProvider } from "../opencomputer/agents/funding/lib/research-provider";
import { SecClient } from "../opencomputer/agents/funding/lib/sec-http";
import { quillworkSec, quillworkSite } from "../test/fixtures/quillwork";
import { testConfig } from "../test/fixtures/world";

const sec = quillworkSec();
const web = quillworkSite();
let t = Date.parse("2026-10-05T12:00:00Z");
const report = await runLookup(
  { url: "quillwork.example", lookupId: "lk_example0000000000000" },
  { config: testConfig(), sec: new SecClient({ userAgent: "example ops@research.example", requestsPerSecond: 2, fetchFn: sec.fetchFn, sleep: async () => {}, now: () => t }), research: new UnavailableProvider("context.dev not enabled (dry run)"), hop: web.hop, resolve: web.resolve, now: () => (t += 7) },
);
writeFileSync("examples/dry-run-report.md", `<!-- Generated by \`npx tsx scripts/example-report.ts\` from synthetic fixtures (invented company, people and CIKs). -->\n\n${renderReport(report)}\n`);
writeFileSync("examples/dry-run-result.json", JSON.stringify(compactReport(report, { planned: true, tables: [] }), null, 2) + "\n");
console.log(renderReport(report));
